### ISSUE TITLE
Permissions with TweetAsync

### ISSUE THREAD

**Issue by RobbyRobbyRobby** [JoeMayo/LinqToTwitter#119] opened 2018-03-22 02:05 UTC
Hi,

I am stuck with .TweetAsync().  Having tried for a few days to figure it out I have decided to ask for help.

I have requested and received tokens for SingleUser and used them in the TwitterContext via a SingleUserInMemoryCredentialStore.  

Twitter's console confirms I have read/write/directmessage permissions.

I have refreshed the tokens to make sure there is no expiration, scope change or other issues.

I can submit and destroy favourites so I believe read/write is working.

However I get permissions issues (Error code 32) when trying to TweetAsync().

```
LinqToTwitter.TwitterQueryException: Could not authenticate you. - Please visit the LINQ to Twitter FAQ (at the HelpLink) for help on resolving this error.
   at LinqToTwitter.TwitterErrorHandler
```

Can someone confirm that this works for them?  I am using LinqToTwitter V4.2.1 but have also tried with V4.1.0.

Thanks!
Rob.

P.S.  This is a great library!  Thanks .

**Comment by JoeMayo** [comment] 2018-03-22 04:47
Hi Rob,

401 errors are the worst. Here are a few ideas:

1. I'm taking a guess that you've been working through the [401 FAQ](https://github.com/JoeMayo/LinqToTwitter/wiki/LINQ-to-Twitter-FAQ#1-i-get-a-401-unauthorized-exception-how-to-i-figure-out-the-problem). Sometimes it's more than one issue. If you find a reason for this and I don't have it in the 401 FAQ, I would appreciate if you shared it with me.
2. Did you try the [TweetAsync demo in ConsoleDemos](https://github.com/JoeMayo/LinqToTwitter/blob/master/Samples/net46/CSharp/ConsoleSamples/StatusDemos.cs)? If that works, maybe it won't be hard to find the delta between your code.
3. Did you try writing a simple console program yourself to isolate your code? That gets other things out of the way so you can see things more clearly.
4. What type of application are you building? The techniques between desktop and web are different and you can see how that works in the samples.
5. Step through the code an make sure you've loaded all of the credentials in SingleUserInMemoryCredentialStore. If you accidentally miss one, you'll get the 401.
6. What is the text parameter for TweetAsync? Does it have special characters? I though I pretty much solved all the character encoding issues by now, but that has been known to cause problems.
7. Look at all of the Exception data and look for any potential HTML code that the Twitter API might have sent back.

Hope this helps,

Joe

**Comment by RobbyRobbyRobby** [comment] 2018-03-22 19:45
After going through all those again to be sure, it looks like it was the test string...  

It had a @ and an ! in it, but not sure where the issue was yet.  (I got it to work late, then went to bed)

I'll look further today and let you know wat I find.

**Comment by RobbyRobbyRobby** [comment] 2018-03-22 23:59
Ok, as soon as I put an @user in it, it fails.

"This is the second tweet from TweedForTwit" - works

"This is the second tweet from @TweedForTwit" - fails.

This is in UWP app running .netcore version 6.

**Comment by winuser** [comment] 2018-09-01 15:32
I have the same issue. If I try to tweet something that includes an hashtag or a user mention I get "Could not authenticate you".
It's an UWP app.

**Comment by JoeMayo** [comment] 2018-09-01 19:10
Having trouble reproducing - just tried this:

https://twitter.com/Mayoster/status/1035966267847372801

using the UwpSamples project: https://github.com/JoeMayo/LinqToTwitter/tree/master/Samples/uap10.0/CSharp/UwpSamples

BTW, I just pushed an update that changes the default URL to http://127.0.0.1 because Twitter's callback_url doesn't accept http://localhost anymore, so you'll want to pull that.

**Comment by winuser** [comment] 2018-09-01 19:12
If I reference the uap10 library I have this issue. I figured out that referencing the uwp + netstandard ones, I can tweet normally.

**Comment by JoeMayo** [comment] 2018-09-01 19:37
Does that solve your problem?

**Comment by winuser** [comment] 2018-09-01 19:50
Yes, it fixed the "could not authenticate you" issue so that I can tweet normally.

I tried with a test app and I always hit the issue by using the uap10 package. No issues with the uwp+netstandard.

**Comment by JoeMayo** [comment] 2020-03-29 02:32
Closing - wasn't ever able to reproduce.

**Closed by JoeMayo** 2020-03-29 02:32 UTC
