### ISSUE TITLE
Showing Direct Message now throws "Sorry, that page does not exist." error

### ISSUE THREAD

**Issue by johnkamau** [JoeMayo/LinqToTwitter#142] opened 2018-09-18 09:37 UTC
This api now no longer works.

https://github.com/JoeMayo/LinqToTwitter/wiki/Showing-Direct-Messages

**Comment by ismail58** [comment] 2018-09-20 07:29
https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/guides/direct-message-migration

**Comment by johnkamau** [comment] 2018-09-20 07:51
My bad, I had thought that the "Show Direct Messages" api was using the new spec. Seems the new api is quite, lean. DMs have no sender info, at all.

**Comment by ErenSongur** [comment] 2018-09-20 13:51
We are getting the same exception. Is this caused by the retirement of the API? If so, will the new release of Linq2Twitter handle this? Can you guide us for the future please?

Thanks.

**Comment by JoeMayo** [comment] 2018-09-24 15:28
Just released v5.0.0: http://bit.ly/2zpY0Kf supporting new Direct Message Events. The Console Samples have [Direct Message Events Demos](https://github.com/JoeMayo/LinqToTwitter/blob/master/Samples/net46/CSharp/ConsoleSamples/DirectMessageEventsDemos.cs).

**Comment by martani** [comment] 2018-09-24 23:57
Also notice you can only access the last 30 days of direct messages now (effective as a few days ago): https://twittercommunity.com/t/direct-messages-events-show-not-returning-the-direct-message-even-when-it-exists

Even if you have the ID of the message, you can't read it or delete it through the API.

**Comment by ErenSongur** [comment] 2018-12-04 07:17
Hi, 
I upgraded to version v5.0.0 but I'm still getting the error "Sorry, that page does not exist."

My query:
Line 66: var latestTweets =
                        (twitterContext.Value.DirectMessage.Where(search =>
                            search.Type == DirectMessageType.SentTo &&
                            search.CreatedAt < DateTime.Now.AddMilliseconds(-TaskPeriod) &&
                            search.Count == 200 && search.FullText == true)).ToList();


Error Log:
ERROR 2018-11-30 11:37:20,972 [4    ] nels.Twitter.TwitterDirectMessagePolling - One or more errors occurred.
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at LinqToTwitter.TwitterQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Sestek.Voc.Sma.Application.Channels.Twitter.TwitterDirectMessagePolling.Search() in C:\Channels\Twitter\TwitterDirectMessagePolling.cs:line 66
Sorry, that page does not exist.

**Comment by JoeMayo** [comment] 2020-04-03 04:26
Closing - Twitter deprecated the previous version of direct messages a while ago and replaced with a new direct message event API, documented here: 

[Direct Message Events](https://github.com/JoeMayo/LinqToTwitter/wiki/Working-with-Direct-Messages)

[@JoeMayo](https://twitter.com/JoeMayo)

**Closed by JoeMayo** 2020-04-03 04:26 UTC
