### ISSUE TITLE
Object reference not set to an instance of an object when using linq to twitter query in Xamarin Android project

### ISSUE THREAD

**Issue by moshemc1** [JoeMayo/LinqToTwitter#251] opened 2022-01-05 07:40 UTC
I am using linqtotwitter 5.1.3 in visual studio 2019 Xamarin android project to search tweets.
My code:
try
    {
      var credentialStore = new InMemoryCredentialStore
      {
          ConsumerKey = "xxxxxxxxxxx",
          ConsumerSecret = "xxxxxxxxxxxxxx"
      };
      var authorizer = new ApplicationOnlyAuthorizer { CredentialStore = credentialStore };
await authorizer.AuthorizeAsync();
      var twitterCtx = new TwitterContext(authorizer);
      var searchResponse = await (from search in twitterCtx.Search
                               where search.Type == SearchType.Search
                               && search.Query == "linq to"
                            select search).SingleOrDefaultAsync();
      if (searchResponse?.Statuses != null)
      {
          foreach (var tweet in searchResponse.Statuses)
          {
             MainActivity.WriteLogMsg("User: " + tweet.User.ScreenNameResponse + " tweet: " + 
             tweet.Text);
          }
      }
    }
    catch (System.Exception exc)
    {
        MainActivity.WriteLogMsg("MainActivity ReadTwitter com.twitter.android " + exc.Message);
        if (exc.InnerException != null)
        {
            MainActivity.WriteLogMsg("MainActivity ReadTwitter com.twitter.android " + 
            exc.InnerException.Message);
            MainActivity.WriteLogMsg("Stack: " + exc.StackTrace);
        }
    }
I get:
Wednesday 2022-01-05 09:18:57 MainActivity OnCreate Twitter Object reference not set to an instance of an object
Wednesday 2022-01-05 09:18:57 Stack:   at LinqToTwitter.TwitterQueryProvider.ExecuteAsync[TResult] (System.Linq.Expressions.Expression expression) [0x00082] in <57e07312c5714a50aea9b833bc55835c>:0 
  at LinqToTwitter.TwitterExtensions.SingleOrDefaultAsync[T] (System.Linq.IQueryable`1[T] query) [0x0007e] in <57e07312c5714a50aea9b833bc55835c>:0 
  at Chatting.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x001d5] in <2eadc6f46725495982257d3b4e3c936b>:0

**Comment by JoeMayo** [comment] 2022-01-06 05:47
I've been trying to reproduce but haven't so far. Looking at the Stack Trace, it seems like you're building the query in `OnCreate`. If so, there might be an async problem. That's because code needs to be async from the top down. Here's a sample that's a little old, but works with Xamarin Forms:

    https://github.com/JoeMayo/LinqToTwitter/tree/main/Samples/LinqToTwitter5/Xamarin/NetStd

What I did there was to build a `TweetingViewModel`:

    public class TweetingViewModel : INotifyPropertyChanged
    {
        List<Tweet> tweets;
        public List<Tweet> Tweets
        {
            get { return tweets; }
            set
            {
                if (tweets == value) return;

                tweets = value;
                OnPropertyChanged();
            }
        }

        public async Task InitTweetViewModel()
        {
            string consumerKey = "";
            string consumerSecret = "";

            var authSvc = DependencyService.Get<ILinqToTwitterAuthorizer>();
            IAuthorizer auth = authSvc.GetAuthorizer(consumerKey, consumerSecret);

            await auth.AuthorizeAsync();

            var ctx = new TwitterContext(auth);

            Search searchResponse = await
                (from search in ctx.Search
                 where search.Type == SearchType.Search &&
                       search.Query == "\"Twitter\""
                 select search)
                .SingleAsync();

            Tweets =
                (from tweet in searchResponse.Statuses
                 select new Tweet
                 {
                     StatusID = tweet.StatusID,
                     ScreenName = tweet.User.ScreenNameResponse,
                     Text = tweet.Text,
                     ImageUrl = tweet.User.ProfileImageUrl
                 })
                .ToList();
        }

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            if (propertyName == null)
                throw new ArgumentNullException("Can't call OnPropertyChanged with a null property name.", propertyName);

            PropertyChangedEventHandler propChangedHandler = PropertyChanged;
            if (propChangedHandler != null)
                propChangedHandler(this, new PropertyChangedEventArgs(propertyName));
        }

Notice how `InitTweetViewModel` is `async`. Then, I built a View page that used this `TweetView`:

    public partial class TweetView : ContentPage
    {
        readonly TweetingViewModel tweetVM = new TweetingViewModel();

        public TweetView()
        {
            InitializeComponent();
        }

        protected override async void OnAppearing()
        {
            base.OnAppearing();

            BindingContext = tweetVM;
            try
            {
                await tweetVM.InitTweetViewModel();
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.ToString());
            }
        }
    }

Notice how the `OnAppearing` method is `async`. In my App, I specified `TweetView` as the `MainPage`:

    public partial class App : Application
	{
		public App ()
		{
			InitializeComponent();

			MainPage = new TweetView();
		}

		protected override void OnStart ()
		{
			// Handle when your app starts
		}

		protected override void OnSleep ()
		{
			// Handle when your app sleeps
		}

		protected override void OnResume ()
		{
			// Handle when your app resumes
		}
	}

Maybe you can trace your app as high through the call stack as possible to ensure it's async all the way up. Is it Xamarin Forms or Native Android (don't know if I have the naming correct)?

**Comment by moshemc1** [comment] 2022-01-06 06:24
Good morning joe,
Originally the call was in async method called ReadTwitter wiich is executed when a notification from twitter arrives the code:
public async static void ReadTwitter(StatusBarNotification sbn)
{
    string pk = sbn.PackageName;
    case "com.facebook.katana":
						tp = "c";
						pid = "c336699";
						gn = Application.Context.Resources.GetString(Resource.String.Facebook);
						iname = "facebook";
						break;
					case "com.instagram.android":
						tp = "c";
						pid = "i606162";
						gn = Application.Context.Resources.GetString(Resource.String.Instagram);
						iname = "instagram";
						break;
					case "org.telegram.messenger":
						tp = "x";
						pid = "x505152";
						gn = Application.Context.Resources.GetString(Resource.String.Telegram);
						iname = "telegram";
						break;
					case "com.twitter.android":
						tp = "t";
						pid = "t98765";
						gn = Application.Context.Resources.GetString(Resource.String.Twitter);
						iname = "twitter";
                                                string contenttw = null;
						string titletw = null;
						try
						{
							Bundle bndltw = sbn.Notification.Extras;
							if (bndltw != null)
							{
								ICollection<string> ks = bndltw.KeySet();
								if (ks != null)
								{
									contenttw =  bndltw.Get("android.text").ToString();
									titletw = bndltw.Get("android.title").ToString();
								}
							}
                                                        var credentialStore = new InMemoryCredentialStore
							{
								ConsumerKey = "xxxxxxx",
								ConsumerSecret = "xxxxxxxxxxxxx"
							};
							var authorizer = new ApplicationOnlyAuthorizer { CredentialStore = credentialStore };
							await authorizer.AuthorizeAsync();
							if (authorizer == null)
							{
								MainActivity.WriteLogMsg("authorizer is null");
								break;
							}
							var twitterCtx = new TwitterContext(authorizer);
							if (twitterCtx == null)
							{
								MainActivity.WriteLogMsg("twitterCtx is null");
								break;
							}
							var searchResponse = await (from search in twitterCtx.Search
														where search.Type == SearchType.Search
														   && search.Query == contenttw
														select search)
															 .SingleOrDefaultAsync();
							if (searchResponse?.Statuses != null)
							{
								foreach (var tweet in searchResponse.Statuses)
								{
									MainActivity.WriteLogMsg("User: " + tweet.User.ScreenNameResponse + " 
                                                                        tweet: " + tweet.Text);
								}
							}
						}
						catch (System.Exception exc)
						{
							MainActivity.WriteLogMsg("MainActivity ReadTwitter com.twitter.android " + 
                                                         exc.Message);
							if (exc.InnerException != null)
							{
								MainActivity.WriteLogMsg("MainActivity ReadTwitter com.twitter.android " + 
                                                                 exc.InnerException.Message);
                                                              MainActivity.WriteLogMsg("Stack: " + exc.StackTrace);
							}
						}
						break;
                                   }
                        ]
the result was the same.
i
I added it to MainActivity just to test without the need to wait for notification from twitter and made it async:
protected async override void OnCreate(Bundle savedInstanceState)

**Comment by JoeMayo** [comment] 2022-01-07 04:54
Still no luck. Can you create a small sample app that reproduces the problem? 

Maybe push it on a branch that I can check out or DM me your email on Twitter.

**Comment by moshemc1** [comment] 2022-01-07 09:28
Hi joe,
Maybe the problem is in my twitter developer account?
![image](https://user-images.githubusercontent.com/97153548/148522839-c76b40c7-447f-46e1-b8ed-816347936e0f.png)

**Comment by JoeMayo** [comment] 2022-01-07 18:01
Everything looks correct. Since you're using Application Only, the callback doesn't come into play either.

**Comment by JoeMayo** [comment] 2022-01-23 22:59
Just following up - if you wanted to share a small sample that reproduces the problem, I'll take a look. Otherwise, I'll close as non-reproducible.

**Comment by moshemc1** [comment] 2022-01-24 07:20
Hi Joe, I wrote a small sample based on your example and it works fine.
The problem is when I do exactly the same in my application it doesn't work.
When I start this new application from my original application it works, I don't understand why

**Comment by JoeMayo** [comment] 2022-02-01 18:14
Sorry, closing as non-reproducible. If we can figure out how to reproduce, I can take another look.

**Closed by JoeMayo** 2022-02-01 18:14 UTC
