### ISSUE TITLE
Error in production

### ISSUE THREAD

**Issue by kshitijsharmanet** [JoeMayo/LinqToTwitter#118] opened 2018-03-21 21:17 UTC
Hello, 

I am trying to use below code to post media to twitter using linq2twitter

    //{
            _logger.LogInformation("Starting ProcessUploadTwitter");
            var auth = new SingleUserAuthorizer
            {

                CredentialStore = new InMemoryCredentialStore()
                {

                    ConsumerKey = oauth.ApiKey,
                    ConsumerSecret = oauth.ApiSecret,
                    OAuthToken = oauth.ApplicationToken,
                    OAuthTokenSecret = oauth.ApplicationTokenSecret

                }

            };
            var twitterCtx = new TwitterContext(auth);
            string mediaCategory = "tweet_image";
            _logger.LogInformation("TWEETING FILE= " + file);
            var imageUploadTasks =
           new List<Task<Media>>
           {
                    twitterCtx.UploadMediaAsync(System.IO.File.ReadAllBytes(file), "image/jpg", mediaCategory),
           };
            _logger.LogInformation("MEDIA UPLOADED TO TWEETER- WAITING TO TWEET THE MEDIA");
            await Task.WhenAll(imageUploadTasks);
            List<ulong> mediaIds =
            (from tsk in imageUploadTasks
             select tsk.Result.MediaID)
            .ToList();

            Status tweet = await twitterCtx.TweetAsync(tenant.Domain, mediaIds);
            _logger.LogInformation("MEDIA TWEETED");
        

It works fine in dev (locally) but in production I am getting below err:

502 - Web server received an invalid response while acting as a gateway or proxy server.

What could be the reason?

**Comment by JoeMayo** [comment] 2018-03-21 21:58
Hi,

If possible/practical, try to log onto the server, so you're in the same environment. Either create a test site or a text console application that does the same thing as the code above. This should mirror an environment similar (identical) to production. Then run Fiddler to watch the HTTP traffic, run the code, and observe the response on Fiddler. Alternatively/Additionally, make sure you've captured all of the error data, including stack trace and response from the server returning the error. What you're showing is just an error message, but you need more context. You're looking for the entire message and in the case of a 5XX, this is often an HTML message that contains more error details. It sounds like you might have a proxy server between your code and the Twitter API. I've included a proxy property on TwitterContext (twitterCtx), but that was for back in the Silverlight days and I don't know if that's a viable alternative or not.

Just a few ideas of things to try because it looks like one of those situations where you have to work with the local environment/infrastructure to figure out what's causing the problem.

[@JoeMayo](https://twitter.com/JoeMayo)

**Comment by kshitijsharmanet** [comment] 2018-03-22 01:04
@JoeMayo , This for the quick response Joe. Yes, I am logging errors but for some reason nothing get logged after below line 
_logger.LogInformation("MEDIA UPLOADED TO TWEETER- WAITING TO TWEET THE MEDIA");

I will try to change code to get error details. But you are right it could be because of proxy. The application is hosted on an AWS virtual machine. I will keep you posted on it. 

Thanks for the pointers. 

Thanks,
Kshitij

**Comment by kshitijsharmanet** [comment] 2018-03-22 10:47
@JoeMayo 
Hello Joe,

I was able to capture the error. Please review below. 

Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException
   at System.Net.Http.WinHttpHandler.HandleAsyncException(System.Net.Http.WinHttpRequestState, System.Exception)
   at System.Net.Http.WinHttpHandler+<StartRequest>d__101.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


Thanks,
Kshitij

**Comment by JoeMayo** [comment] 2018-03-22 19:06
This looks a little different. Notice that it's a FileLoadException and the only place you're loading a file is:

                twitterCtx.UploadMediaAsync(System.IO.File.ReadAllBytes(file), "image/jpg", mediaCategory),

I would focus on the call to `System.IO.File.ReadAllBytes(file)`. Look at the path to make sure it exists and that your code has permission to access it. Look at any InnerExceptions if possible, just in case you're getting OutOfMemoryException too. Check out the Twitter API specs on max image sizes to guard against that possibility (e.g. inspect the size of the image and notify the user about the limitation).

Joe

**Comment by kshitijsharmanet** [comment] 2018-03-22 19:25
@JoeMayo 
Thanks for the response Joe. However, the above mentioned line of code execute as expected as in my logs I can see log entry for  MEDIA UPLOADED TO TWEETER- WAITING TO TWEET THE MEDIA

It fails on 
  Status tweet = await twitterCtx.TweetAsync(tenant.Domain, mediaIds);

Thanks,
Kshitij

**Comment by kshitijsharmanet** [comment] 2018-03-22 19:36
Also, just to make things clear.. just before uploading to twitter my app is uploading files to Facebook and Flickr which both works just fine.

Thanks,
Kshitij

**Comment by JoeMayo** [comment] 2018-03-23 16:55
What is `tenant.Domain`?

**Comment by kshitijsharmanet** [comment] 2018-03-23 16:59
It is the domain for the application. This is a SaaS application and
tenants (you can think them as multiple websites) share the same code base
and db. So at rum time everything is decided based on the tenant
properties. One of which is domain.

Kshitij

**Comment by kshitijsharmanet** [comment] 2018-03-23 21:26
My best guess is that my prod box is missing one of the dependency but I am not able to pinpoint

**Comment by JoeMayo** [comment] 2018-03-23 22:49
I should have been more clear - What is the text produced by `tenant.Domain`? The parameter passed is type string and, on rare occasions, I encounter encoding issues. What if your firewall interpreted that value as something it doesn't allow? Maybe try that exact text in my sample program to see if it runs on both your server and dev box.

**Comment by kshitijsharmanet** [comment] 2018-03-23 22:57
Alright, I'll try that. The text is something like www.Kshitijsharma.net.

I'll try to use a static string to test and update back.

Kshitij

**Comment by kshitijsharmanet** [comment] 2018-03-24 01:35
Alright, I think I can now tell on what line code is breaking.  I added below log entries

  _logger.LogInformation("TWITTER UPLOADED MEDIA IDS=" + mediaIds);
   Status tweet = await twitterCtx.TweetAsync(tenant.Name, mediaIds);
   
But it was never logged. The code is breaking on 

   await Task.WhenAll(imageUploadTasks);
            List<ulong> mediaIds =
            (from tsk in imageUploadTasks
             select tsk.Result.MediaID)
            .ToList();

It is never reaching on

  Status tweet = await twitterCtx.TweetAsync(tenant.Name, mediaIds);

Below is the log entry from server:

2018-03-24T06:22:27.0336469+05:30 0HLCH44B4D3SV [INF] Flickr UPLOAD COMPLETE (d81172cb)
2018-03-24T06:22:27.0336469+05:30 0HLCH44B4D3SV [INF] Processing TWEETER Upload (8f4423c7)
2018-03-24T06:22:27.3148919+05:30 0HLCH44B4D3SV [INF] Starting ProcessUploadTwitter (f904521c)
2018-03-24T06:22:27.3305001+05:30 0HLCH44B4D3SV [INF] TWEETING FILE= XXXX.jpg(32791990)
2018-03-24T06:22:27.4242606+05:30 0HLCH44B4D3SV [INF] 
MEDIA UPLOADED TO TWEETER- WAITING TO TWEET THE MEDIA (2ec90e87)

**Comment by JoeMayo** [comment] 2018-03-24 04:04
Is your code `async` all the way up the call chain? Try wrapping that in a try/catch, AggregateException I believe but catch Exception too just in case, and logging InnerExceptions (notice the plural).

**Comment by kshitijsharmanet** [comment] 2018-03-24 13:44
Yes, So the calling method is 

        [HttpPost]
        public async Task<IActionResult> ProcessSingleUpload(IFormFile file)

and below is the calling code for that method

   try
                            {
                                await ProcessUploadTwitter(acc, imagePPath);
                            }
                            catch (Exception exp)
                            {
                                _logger.LogInformation("ERROR [" + exp.Message + "]");
                            }
                          _logger.LogInformation("TWEETER UPLOAD COMPLETE");

But code never reaches in the exception block for some reason.

**Comment by JoeMayo** [comment] 2018-03-24 19:34
What about an [AppDomain.UnhandledException](https://msdn.microsoft.com/en-us/library/system.appdomain.unhandledexception%28v=vs.110%29.aspx) handler?

**Comment by kshitijsharmanet** [comment] 2018-03-24 21:10
Thanks for the pointer. I was able to log the exception:

2018-03-25T02:16:24.1703562+05:30 [INF] UnhandledException Has been Caught : Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) (a086bf64)

**Comment by JoeMayo** [comment] 2020-03-29 02:30
Closing - I was never able to reproduce this.

**Closed by JoeMayo** 2020-03-29 02:30 UTC
