### ISSUE TITLE
Application is Waiting on search

### ISSUE THREAD

**Issue by spider58** [JoeMayo/LinqToTwitter#178] opened 2020-04-20 15:11 UTC
Hi,

I want to get extended_entities object from twitter via twitter link

Example
link : https://twitter.com/FloodSocial/status/869318041078820864/video/1

What i want to get:
https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/extended-entities-object

How can i do that.

I tried somw codes but but first i tried to search "coronavirus".
 My application is waiting on here.

```
Dim Response As Search =
            Await (From search In twitterCtx.Search()
                   Where search.Type = SearchType.Search _
                   AndAlso search.Query = "Coronavirus") _
                  .SingleOrDefaultAsync()
```

My whole code below. What's im doing wrong?.. and 

I have a tweet link 

Thanks.

   ```
 Async Function trySomething() As Task
        Try
            Dim credentials As InMemoryCredentialStore = New InMemoryCredentialStore
            credentials.ConsumerKey = "xxxx"
            credentials.ConsumerSecret = "xxxx"
            credentials.OAuthToken = "xxxx"
            credentials.OAuthTokenSecret = "xxxx"


            Dim auth As PinAuthorizer = New PinAuthorizer()
            auth.CredentialStore = credentials
            auth.GetPin =
                Function()
                    Console.WriteLine("Next, you'll need to tell Twitter to authorize access. This program will not have access to your credentials, which is the benefit of OAuth. Once you log into Twitter and give this program permission, come back to this console.")
                    Console.WriteLine()
                    Console.Write("Please enter the PIN from Twitter: ")

                    Return Console.ReadLine()
                End Function
            auth.GoToTwitterAuthorization =
            Function(pageLink)
                Dim psi As ProcessStartInfo = New ProcessStartInfo
                With psi
                    .FileName = pageLink
                    .UseShellExecute = True
                End With
                Return Process.Start(psi)
            End Function

            'Await auth.AuthorizeAsync()

            Dim twitterCtx = New TwitterContext(auth)

            Await SearchAsync(twitterCtx)

        Catch ex As Exception

        End Try

    End Function

    Private Async Function SearchAsync(twitterCtx As TwitterContext) As Task


        Dim Response As Search =
            Await (From search In twitterCtx.Search()
                   Where search.Type = SearchType.Search _
                   AndAlso search.Query = "Coronavirus") _
                  .SingleOrDefaultAsync()

        Dim tweets As List(Of Status) = Response.Statuses()

        If Response IsNot Nothing AndAlso Response.Statuses IsNot Nothing Then
            For Each str As Status In tweets
                Console.WriteLine(str.StatusID.ToString() + " " + str.FullText)
            Next
        End If
    End Function
```

**Comment by JoeMayo** [comment] 2020-04-21 16:39
Each Status has an `ExtendedEntities` property that you can access, like this:

```vb
If Response IsNot Nothing AndAlso Response.Statuses IsNot Nothing Then
	For Each str As Status In tweets
		Console.WriteLine(str.StatusID.ToString() + " " + str.FullText)

		If str.ExtendedEntities.MediaEntities.Count > 0 Then
			Console.WriteLine(" - Media URL: " + str.ExtendedEntities.MediaEntities(0).MediaUrl)
		End If
	Next
End If
```

Notice that I checked the `Count` property prior to reading to make sure there was a `MediaEntity`.

[@JoeMayo](https://twitter.com/JoeMayo)

**Comment by spider58** [comment] 2020-04-22 05:53
@JoeMayo Thanks for the answer. But i never reach to line of your code because my program is waiting on below code block, no response, no error code, just waiting.

`Dim Response As Search =
         Await (From search In twitterCtx.Search()
                Where search.Type = SearchType.Search _
                AndAlso search.Query = "Coronavirus") _
               .SingleOrDefaultAsync()`

Do you have an idea why ?

**Comment by JoeMayo** [comment] 2020-04-22 06:50
@spider58 I can't tell by looking at it. Maybe take a look at my [Sample VB Code](https://github.com/JoeMayo/LinqToTwitter/blob/master/Samples/LinqToTwitter5/net48/VB/ConsoleSamplesVB/ConsoleSamplesVB/Program.vb) and compare it to your program. You could also clone or download my repository and run the VB sample on your machine to see what the differences are between the two.

One thought, you might want to make sure that you're using `Async `all the way down the call stack.

**Comment by JoeMayo** [comment] 2020-04-28 03:38
Closing - Unable to reproduce.

**Closed by JoeMayo** 2020-04-28 03:38 UTC
